core: Fix annotation of grl_init() to fix vala bindings
Trying to pass args (argc/argv) to grl.init() failed in vala with the error:
error: Argument 1: Cannot pass unowned ref argument to owned reference parameter
        Grl.init (ref args);
                  ^^^^^^^^

We need to mark the argv as "transfer none" to have it match the
type of args, as done in other GObject libraries with vala bindings.